### PR TITLE
added ticketrelease fields to event table

### PR DESCRIPTION
**Pull request by FDelporte**

### CODE REVIEW

**Comment by josmas** [comment]
runs ok in Ubuntu 64b (no checksum errors)

**Comment by josmas** [comment]
Probably not one to merge though, without the extra code that should go with it?

**Comment by FDelporte** [comment]
indeed, not yet to be merged, was hoping to get the counter up on 24pullrequests ;-)

**Comment by tangentfairy** [comment]
Let's close this until it is ready for a final review, then you can reopen it. Let me know if you have any questions! :)

**Pull request closed without merging**
